language: python

cache: pip

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - python -m pip install mypy
  - python -m pip install git+https://github.com/mideind/Tokenizer#egg=tokenizer

script:
  - python -m pip install -e .
  - mypy src/reynir/__init__.py
  - python -m pytest

notifications:
  slack: greynir:38FfPr1S8oZRNFMmt47mzT3z
